/**
 * netflop
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Netflop);
  }
}(this, function(expect, Netflop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Netflop.InlineObject2();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineObject2', function() {
    it('should create an instance of InlineObject2', function() {
      // uncomment below and update the code to test InlineObject2
      //var instane = new Netflop.InlineObject2();
      //expect(instance).to.be.a(Netflop.InlineObject2);
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new Netflop.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property moviesId (base name: "moviesId")', function() {
      // uncomment below and update the code to test the property moviesId
      //var instane = new Netflop.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property seriesId (base name: "seriesId")', function() {
      // uncomment below and update the code to test the property seriesId
      //var instane = new Netflop.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property episodesId (base name: "episodesId")', function() {
      // uncomment below and update the code to test the property episodesId
      //var instane = new Netflop.InlineObject2();
      //expect(instance).to.be();
    });

  });

}));
