version : '3.8'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=postgres
      - MYSQL_USER=postgres
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=netflop
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./project.sql:/docker-entrypoint-initdb.d/project.sql