/**
 * netflop
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Episodes model module.
 * @module model/Episodes
 * @version 1.0
 */
class Episodes {
    /**
     * Constructs a new <code>Episodes</code>.
     * @alias module:model/Episodes
     */
    constructor() { 
        
        Episodes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Episodes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Episodes} obj Optional instance to populate.
     * @return {module:model/Episodes} The populated <code>Episodes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Episodes();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
            }
            if (data.hasOwnProperty('actors')) {
                obj['actors'] = ApiClient.convertToType(data['actors'], 'String');
            }
            if (data.hasOwnProperty('releaseDate')) {
                obj['releaseDate'] = ApiClient.convertToType(data['releaseDate'], 'String');
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'String');
            }
            if (data.hasOwnProperty('quality')) {
                obj['quality'] = ApiClient.convertToType(data['quality'], 'String');
            }
            if (data.hasOwnProperty('season')) {
                obj['season'] = ApiClient.convertToType(data['season'], 'Number');
            }
            if (data.hasOwnProperty('episode')) {
                obj['episode'] = ApiClient.convertToType(data['episode'], 'Number');
            }
            if (data.hasOwnProperty('seriesId')) {
                obj['seriesId'] = ApiClient.convertToType(data['seriesId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Episodes.prototype['id'] = undefined;

/**
 * @member {String} description
 */
Episodes.prototype['description'] = undefined;

/**
 * @member {String} genre
 */
Episodes.prototype['genre'] = undefined;

/**
 * @member {String} duration
 */
Episodes.prototype['duration'] = undefined;

/**
 * @member {String} actors
 */
Episodes.prototype['actors'] = undefined;

/**
 * @member {String} releaseDate
 */
Episodes.prototype['releaseDate'] = undefined;

/**
 * @member {String} creationDate
 */
Episodes.prototype['creationDate'] = undefined;

/**
 * @member {String} quality
 */
Episodes.prototype['quality'] = undefined;

/**
 * @member {Number} season
 */
Episodes.prototype['season'] = undefined;

/**
 * @member {Number} episode
 */
Episodes.prototype['episode'] = undefined;

/**
 * @member {Number} seriesId
 */
Episodes.prototype['seriesId'] = undefined;






export default Episodes;

