/**
 * netflop
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Netflop);
  }
}(this, function(expect, Netflop) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Netflop.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('getEpisodes', function() {
      it('should call getEpisodes successfully', function(done) {
        //uncomment below and update the code to test getEpisodes
        //instance.getEpisodes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavorites', function() {
      it('should call getFavorites successfully', function(done) {
        //uncomment below and update the code to test getFavorites
        //instance.getFavorites(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLikes', function() {
      it('should call getLikes successfully', function(done) {
        //uncomment below and update the code to test getLikes
        //instance.getLikes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMovies', function() {
      it('should call getMovies successfully', function(done) {
        //uncomment below and update the code to test getMovies
        //instance.getMovies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReviews', function() {
      it('should call getReviews successfully', function(done) {
        //uncomment below and update the code to test getReviews
        //instance.getReviews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSeries', function() {
      it('should call getSeries successfully', function(done) {
        //uncomment below and update the code to test getSeries
        //instance.getSeries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideos', function() {
      it('should call getVideos successfully', function(done) {
        //uncomment below and update the code to test getVideos
        //instance.getVideos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postFavorites', function() {
      it('should call postFavorites successfully', function(done) {
        //uncomment below and update the code to test postFavorites
        //instance.postFavorites(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postLogin', function() {
      it('should call postLogin successfully', function(done) {
        //uncomment below and update the code to test postLogin
        //instance.postLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postRegister', function() {
      it('should call postRegister successfully', function(done) {
        //uncomment below and update the code to test postRegister
        //instance.postRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postReviews', function() {
      it('should call postReviews successfully', function(done) {
        //uncomment below and update the code to test postReviews
        //instance.postReviews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
