/**
 * netflop
 * Netflop apis
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Serie {
    "id": number;
    "title": string;
    "description": string;
    "genre": string;
    "duration": string;
    "actors": string;
    "releaseDate": string;
    "creationDate": string;
}

