/**
 * netflop
 * Netflop apis
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface UsersRegisterRequest {
    "email": string;
    "password": string;
    "name": string;
    "surname": string;
    "birthDate": string;
    "newsletter": boolean;
}

